name: Fetch & Build 7-Day Typhoon

on:
  schedule:
    - cron: "0 */3 * * *"   # 每3小時自動運行
  workflow_dispatch: {}      # 可手動執行

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy shapely pyproj

      - name: Run scripts
        run: |
          python scripts/fetch_hko.py || true
          python scripts/normalize_all.py || true
          python scripts/build_ensemble_0_5d.py || true
          python scripts/build_risk_6_7d.py || true
          python scripts/build_hk_impact.py || true

      - name: Commit outputs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data site
          git commit -m "Auto update $(date -u +'%Y-%m-%dT%H:%MZ')" || echo "No changes"
          git push
